locals {
  # Your name.
  creator_tag = "Jeff White"

  # The name of the image definition within the Azure compute gallery where
  # the resulting image will be stored. This image definition must already exist.
  image_definition_name = "debian-11-slurm-20"

  # The version of the resulting image (e.g. "0.0.2").
  image_version = "0.0.7"
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    creator = "${local.creator_tag}"
  }
  #client_id       = ""
  #client_secret   = ""
  image_offer     = "debian-11"
  image_publisher = "Debian"
  image_sku       = "11-gen2"
  #plan_info {
  #  plan_name      = "11-gen2"
  #  plan_product   = "debian-11"
  #  plan_publisher = "Debian"
  #}
  location        = "East US 2"
  vm_size         = "Standard_E2bs_v5"
  subscription_id = "8251e869-3bec-4d80-a8ba-959e8caffb89"
  os_type         = "Linux"
  temp_resource_group_name = "packerTempBuildResources"
  managed_image_name                = "${local.image_definition_name}_${local.image_version}"
  managed_image_resource_group_name = "packerVirtualMachineImages"
  shared_image_gallery_destination {
    subscription         = "8251e869-3bec-4d80-a8ba-959e8caffb89"
    resource_group       = "Stuff"
    gallery_name         = "vmImages"
    image_name           = "${local.image_definition_name}"
    image_version        = "${local.image_version}"
    replication_regions  = ["East US 2"]
    storage_account_type = "Standard_LRS"
  }
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "../ansible/debian-slurm-image.yaml"
  }

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = [
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ]
    inline_shebang  = "/bin/sh -x"
  }
}
