---
- name: Cluster configuration, compute nodes
  hosts: all
  become: true
  remote_user: deploy_user
  vars:
    ansible_ssh_private_key_file: /home/deploy_user/.ssh/id_rsa

  tasks:
  - name: Copy munge key
    ansible.builtin.copy:
      dest: /etc/munge/munge.key
      src: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: 0600
    notify: Restart munge

  - name: Start munge
    ansible.builtin.service:
      name: munge
      state: started
      enabled: true

  - name: Create cgroup.conf
    ansible.builtin.copy:
      dest: /etc/slurm/cgroup.conf
      owner: root
      group: root
      mode: 0644
      content: |
        CgroupAutomount=yes
        CgroupMountpoint=/sys/fs/cgroup
        ConstrainCores=yes
        ConstrainDevices=yes
        ConstrainKmemSpace=no
        ConstrainRAMSpace=yes
        ConstrainSwapSpace=yes
    notify: Restart slurmd

  - name: Create slurmd spool directory
    ansible.builtin.file:
      dest: /var/spool/slurmd
      owner: slurm
      group: slurm
      mode: 0700
      state: directory

  - name: Get Slurm node info
    ansible.builtin.command: slurmd -C
    register: slurm_node_info

  - name: Append compute node to slurm.conf on the head node
    ansible.builtin.lineinfile:
      path: /etc/slurm/slurm.conf
      line: "{{ slurm_node_info.stdout_lines[0] }}"
    delegate_to: 127.0.0.1

  - name: Push slurm.conf from head node
    ansible.builtin.copy:
      dest: /etc/slurm/slurm.conf
      src: /etc/slurm/slurm.conf
      owner: root
      group: root
      mode: 0644
    notify: Restart slurmd

  - name: Start slurmd
    ansible.builtin.service:
      name: slurmd
      state: started
      enabled: true

  handlers:
    - name: Restart munge
      ansible.builtin.service:
        name: munge
        state: restarted

    - name: Restart slurmd
      ansible.builtin.service:
        name: slurmd
        state: restarted
