---
- name: Base configuration
  hosts: all
  become: true

  tasks:
  - name: Get current date and time
    ansible.builtin.command: date
    register: date_command
    changed_when: false

  - name: Create release file
    ansible.builtin.copy:
      dest: /etc/azure-slurm-release
      mode: 0644
      owner: root
      group: root
      content: |
        BUILD_DATE={{ date_command.stdout }}

  - name: Install packages
    ansible.builtin.package:
      name:
        - sudo
        - vim
        - tmux
        - zsh
        - rsync
        - tcpdump
        - gnupg2
        - jq
        - unzip
        - dnsutils

  - name: Disable swap on boot
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: '\s+swap\s+'
      state: absent
      backup: true

  - name: Ensure /var/log/journal exists
    ansible.builtin.file:
      path: /var/log/journal
      owner: root
      group: systemd-journal
      state: directory
      mode: 02755

  - name: Add key for Ansible repo
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367
  
  - name: Add Ansible repo
    ansible.builtin.copy:
      dest: /etc/apt/sources.list.d/ansible.list
      owner: root
      group: root
      mode: 0644
      content: |
        deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main
  
  - name: Install Ansible
    ansible.builtin.apt:
      name: ansible
      update_cache: true

  - name: Install Slurm packages
    ansible.builtin.package:
      name:
        - slurm-wlm
        - slurm-wlm-basic-plugins
        - slurm-wlm-basic-plugins-dev
        - slurm-wlm-doc
        - slurm-wlm-torque
        - slurmdbd
        - slurmrestd
        - libpam-slurm
        - libslurm-dev
        - libslurm-perl
        - munge
        - mariadb-server
        - mariadb-client
        - python3-pymysql
        - mailutils
      state: present

  - name: Disable Slurm daemons
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: false
      state: stopped
    loop:
      - slurmd
      - slurmctld
      - slurmdbd
      - slurmrestd
      - mariadb
      - munge

  - name: Create systemd configuration directories for Slurm daemons
    ansible.builtin.file:
      dest: "/etc/systemd/system/{{ item }}.service.d"
      owner: root
      group: root
      mode: 0644
      state: directory
    loop:
      - munge
      - mariadb
      - slurmdbd
      - slurmctld
      - slurmrestd
      - slurmd

  - name: Create systemd unit override files for Slurm daemons
    ansible.builtin.copy:
      dest: "/etc/systemd/system/{{ item }}.service.d/overrides.conf"
      content: |
        [Service]
        Restart=on-failure
    loop:
      - munge
      - mariadb
      - slurmdbd
      - slurmctld
      - slurmrestd
      - slurmd
    notify: Restart systemd

  - name: Create deploy group
    ansible.builtin.group:
      name: deploy_user
      gid: 980

  - name: Create deployment user
    ansible.builtin.user:
      name: deploy_user
      uid: 1001
      group: deploy_user
      shell: /bin/bash

  - name: Create .ssh directory for deployment user
    ansible.builtin.file:
      path: /home/deploy_user/.ssh
      mode: 0700
      owner: deploy_user
      group: deploy_user
      state: directory

  - name: Create deployment user's SSH keys
    community.crypto.openssh_keypair:
      path: /home/deploy_user/.ssh/id_rsa
      owner: deploy_user
      group: deploy_user
    register: deployment_user_ssh_keys

  - name: Create deployment user's authorized_keys
    ansible.builtin.copy:
      dest: /home/deploy_user/.ssh/authorized_keys
      mode: 0600
      owner: deploy_user
      group: deploy_user
      content: |
        {{ deployment_user_ssh_keys.public_key }}

  - name: Give deployment user sudo privileges
    ansible.builtin.copy:
      dest: /etc/sudoers.d/deploy_user
      mode: 0600
      owner: root
      group: root
      content: |
        %deploy_user ALL=(ALL) NOPASSWD: ALL

  - name: Upgrade all other packages
    ansible.builtin.command: apt upgrade -y

  - name: Remove apt cache
    ansible.builtin.command: apt-get clean

  handlers:
  - name: Restart systemd
    ansible.builtin.service:
      daemon_reload: true